"""Create Chatbot table

Revision ID: e06250301c15
Revises:
Create Date: 2021-04-27 00:05:46.900689

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e06250301c15"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatbot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chatbot")
    # ### end Alembic commands ###
